// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rddlopykjxkreaqikgit.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkZGxvcHlranhrcmVhcWlrZ2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk0MTcxNDYsImV4cCI6MjA0NDk5MzE0Nn0.9jCp_geaPFTd84rmTJtG96tLJSBUMRTOai8MbNxYwv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);